// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3t-eSURh2TFkdf_-T5ljcFiUooo8IITk',
    appId: '1:586347800341:web:37ca61c56586b3e2d7eb1c',
    messagingSenderId: '586347800341',
    projectId: 'fir-demo-6d23f',
    authDomain: 'fir-demo-6d23f.firebaseapp.com',
    storageBucket: 'fir-demo-6d23f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIaCMeBLo3zLbPlZzooUyrm2tMqmnPFTY',
    appId: '1:586347800341:android:a8d6eafd7035651ed7eb1c',
    messagingSenderId: '586347800341',
    projectId: 'fir-demo-6d23f',
    storageBucket: 'fir-demo-6d23f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4SgtTTPvyAuIcJlFaZEmWTAVbV_p5PSI',
    appId: '1:586347800341:ios:9ef4ef375ae3814cd7eb1c',
    messagingSenderId: '586347800341',
    projectId: 'fir-demo-6d23f',
    storageBucket: 'fir-demo-6d23f.appspot.com',
    iosClientId: '586347800341-oe5j5p18h84qsjqoaq2khu8u9l8iocvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemoWithProvider',
  );
}
